apiVersion: v2
name: epro-projekt
home: https://github.com/spring-projects/spring-boot/epro-projekt
type: application
description: "Project for EPRO by Norman Dobrovsky, Artur Mustaf and Nikita Stephan"
sources:
- https://github.com/spring-projects/spring-boot/epro-projekt
version: "1.0.2"
dependencies:
  - name: postgresql
    version: ~11.1.3
    repository: https://charts.bitnami.com/bitnami