spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_CONNECT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  error:
    include-stacktrace: never